### ISSUE TITLE
训练时出现“StopIteration”错误

### ISSUE THREAD

**Issue by chiyandetaotie** [BBuf/Keras-Semantic-Segmentation#5]
当我运行这句话时，出现了问题
python  train.py --save_weights_path="/media/yl/4T_Data/Keras-Semantic-Segmentation-master/weights/fcn8" \
 --train_images="/media/yl/4T_Data/data/group2/scene2/composite" \
 --train_annotations="/media/yl/4T_Data/data/group2/scene2/mask" \
 --val_images="/media/yl/4T_Data/data/group2/scene2/composite2" \
 --val_annotations="/media/yl/4T_Data/data/group2/scene2/mask2" \
 --n_classes=8 --input_height=512 --input_width=512 --model_name="fcn8"

报错如下：
/home/yl/anaconda3/envs/keras-seg/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/yl/anaconda3/envs/keras-seg/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Model output shape :  (None, 270400, 8)
Epoch 1/1
Traceback (most recent call last):
  File "train.py", line 116, in <module>
    m.fit_generator(G, 100, validation_data=G2, validation_steps=20,  epochs=1)
  File "/home/yl/anaconda3/envs/keras-seg/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/yl/anaconda3/envs/keras-seg/lib/python3.6/site-packages/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/yl/anaconda3/envs/keras-seg/lib/python3.6/site-packages/keras/engine/training_generator.py", line 155, in fit_generator
    generator_output = next(output_generator)
  File "/home/yl/anaconda3/envs/keras-seg/lib/python3.6/site-packages/keras/utils/data_utils.py", line 785, in get
    raise StopIteration()
StopIteration

这个具体是哪有问题，您能解答一下吗

**Comment by chiyandetaotie** [comment]
您好，出现这个错误时使用的是自己的数据集，使用您的数据集没有出现这种问题。我的数据集是8分类的（包括背景），而且也制作了mask，我不清楚我的数据集问题在哪。您的数据集中图片位深度为8, 我的数据图片是rgb的彩色图片，位深度是24，这个会有影响吗？

**Comment by chiyandetaotie** [comment]
您的数据图片是单通道的吗？我的数据图片是三通道的，请问我这个应该修改代码的哪个部分，使得我的数据可以正常读入？
