### ISSUE TITLE
测试时出现问题

### ISSUE THREAD

**Issue by chiyandetaotie** [BBuf/Keras-Semantic-Segmentation#6]
当我运行
python test.py  时出现错误：
Traceback (most recent call last):
  File "test.py", line 10, in <module>
  File "/home/user/yzc/yanglin/Keras-Semantic-Segmentation-master/Models/FCN8.py", line 2, in <module>
    from keras.models import *
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/keras/backend/__init__.py", line 87, in <module>
    from .tensorflow_backend import *
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 102, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 30, in <module>
    from tensorflow.python.framework import function
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 36, in <module>
    from tensorflow.python.ops import array_ops
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1974, in <module>
    @ops.RegisterGradient("FakeQuantWithMinMaxArgs")
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2085, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 67, in register
    stack = traceback.extract_stack()
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/traceback.py", line 207, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/traceback.py", line 358, in extract
    f.line
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/traceback.py", line 282, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/home/user/anaconda3/envs/keras-seg/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 2817-2818: invalid continuation byte

请问这个该如何解决？

**Comment by chiyandetaotie** [comment]
我修改的test.py文件如下：


import glob
import cv2
import numpy as np
import random
import datetime
import Models, LoadBatches
from Models import FCN8
from Models import FCN32
from Models import Segnet
from Models import MiniUnet
from Models import Unet
from Models import PSPNet
from Models import ICNet
from Models import VGGSegnet
from Models import VGGUnet
from Models import VGGFCN8
from Models import VGGFCN32
from Models import ResNet50_Segnet
from Models import ResNet50_Unet
from Models import ResNet50_FCN8
from Models import ResNet50_FCN32
from Models import MobileNetUnet
from Models import MobileNetFCN8
from Models import MobileNetFCN32
from Models import MobileNetSegnet
from keras.models import load_model

EPS = 1e-12
n_classes = 2
model_name = "fcn8"
images_path = "/home/user/yzc/yanglin/Keras-Semantic-Segmentation-master/data/test/"    
output_path = "/home/user/yzc/yanglin/Keras-Semantic-Segmentation-master/data/output_/"
save_weights_path = "/mnt/data/yzc/yanglin/data/fcn/weights/ex1"  
input_height = 512
input_width = 512
epoch_num = 0

其余地方没有修改，请问我这个如何修改才能不报错

**Comment by BBuf** [comment]
你在文件开头加一个 #coding=utf-8 就可以了

**Comment by BBuf** [comment]
抱歉现在才看到
